Repository Telefonica/mistica-ios, pull requests merged in 2022-01, with the labels that each got.

#156 fix(Tags) Fix tag background colors on dark mode - IOS-7221
  Mistica/Source/Colors/BlauColorPalette.swift
  Mistica/Source/Colors/MovistarColorPalette.swift
  Mistica/Source/Colors/O2ClassicColorPalette.swift
  Mistica/Source/Colors/O2ColorPalette.swift
  Mistica/Source/Colors/VivoColorPalette.swift
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testActiveTagView.with-blau-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testActiveTagView.with-movistar-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testActiveTagView.with-o2-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testActiveTagView.with-o2Classic-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testActiveTagView.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testErrorTagView.with-blau-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testErrorTagView.with-movistar-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testErrorTagView.with-o2-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testErrorTagView.with-o2Classic-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testErrorTagView.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testInactiveTagView.with-blau-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testInactiveTagView.with-movistar-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testInactiveTagView.with-o2-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testInactiveTagView.with-o2Classic-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testInactiveTagView.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testPromoTagView.with-blau-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testPromoTagView.with-movistar-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testPromoTagView.with-o2-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testPromoTagView.with-o2Classic-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testPromoTagView.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testSuccessTagView.with-blau-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testSuccessTagView.with-movistar-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testSuccessTagView.with-o2-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testSuccessTagView.with-o2Classic-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testSuccessTagView.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testTagViewWithIcon.with-blau-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testTagViewWithIcon.with-movistar-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testTagViewWithIcon.with-o2-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testTagViewWithIcon.with-o2Classic-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testTagViewWithIcon.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testWarningTagView.with-blau-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testWarningTagView.with-movistar-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testWarningTagView.with-o2-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testWarningTagView.with-o2Classic-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/TagTests/testWarningTagView.with-vivo-dark-style.png
Labels: bug

#154 Add error animation for feedback view for vivo
  Mistica/Source/Resources/Assets.xcassets/vivo/FeedbackError.dataset/Contents.json
  Mistica/Source/Resources/Assets.xcassets/vivo/FeedbackError.dataset/FeedbackError.json
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorMultilineScrollWithButtons.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorMultilineScrollWithButtons.with-vivo-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorMultilineScrollWithErrorReference.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorMultilineScrollWithErrorReference.with-vivo-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorPrimaryRetryAndSecondaryButtonLink.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorPrimaryRetryAndSecondaryButtonLink.with-vivo-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorPrimaryRetryButton.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorPrimaryRetryButton.with-vivo-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorSecondaryButtonLink.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorSecondaryButtonLink.with-vivo-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorSecondaryPrimaryButtonCustomView.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorSecondaryPrimaryButtonCustomView.with-vivo-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorTitleAndSubtitle.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorTitleAndSubtitle.with-vivo-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorTitleSubtitleAndErrorReference.with-vivo-dark-style.png
  Mistica/Tests/MisticaTests/UI/__Snapshots__/FeedbackTests/testErrorTitleSubtitleAndErrorReference.with-vivo-style.png
Labels: enhancement

#158 feat(Feedback) Add error animation for feedback view for vivo IOS-7087
  Mistica/Source/Components/Feedback/README.md
Labels: documentation

#159 feat(Feedback): Add error animation for feedback view for vivo IOS-7087
  Mistica/Source/Components/Feedback/README.md
Labels: documentation
